#!/bin/bash


RiZoeL_Spam () {
    local regex
    regex='(https?)://github.com/.+/.+'
    if [[ $RiZoeL == "rizoelxspam" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1JpWm9lTFgvUmlab2VMWFNwYW0vYXJjaGl2ZS9NYWluLnppcA==" | base64 -d
    elif [[ $RiZoeL == "ARRAYCORE" ]]
    then
        echo "aHR0cHM6Ly9naXRodWIuY29tL1JpWm9lTFgvUmlab2VMWFNwYW0vYXJjaGl2ZS9NYWluLnppcA==" | base64 -d
    elif [[ $RiZoeL =~ $regex ]]
    then
        if [[ $RiZoeL_BRANCH ]]
        then
            echo "${RiZoeL}/archive/${RiZoeL_BRANCH}.zip"
        else
            echo "${RiZoeL}/archive/Main.zip"
        fi
    else
        echo "aHR0cHM6Ly9naXRodWIuY29tL1JpWm9lTFgvUmlab2VMWFNwYW0vYXJjaGl2ZS9NYWluLnppcA==" | base64 -d
    fi
}


_set_bot () {
    local zippath
    zippath="rizoelxspam.zip"
    echo "••• Downloading RiZoeLXSpam •••"
    wget -q $(RiZoeL_Spam) -O "$zippath"
    echo "  Unpacking Data ..."
    TheRiZoeL=$(zipinfo -1 "$zippath" | grep -v "/.");
    unzip -qq "$zippath"
    echo "Done"
    rm -rf "$zippath"
    sleep 3
    cd $TheRiZoeL
    echo " • RiZoeLXSpam Here. •

    python3 ./startup/run.py ./requirements.txt requirements.txt
    python3 -m RiZoeLXSpam
}

_set_bot
